version: "3.8"

services:

  linkstack:
    hostname: 'linkstack'
    image: 'linkstackorg/linkstack:latest'
    environment:
      TZ: 'Asia/Shanghai'
      SERVER_ADMIN: '<your email address>'
      HTTP_SERVER_NAME: '<your domain>'
      HTTPS_SERVER_NAME: '<your domain>'
      LOG_LEVEL: 'info'
      PHP_MEMORY_LIMIT: '256M'
      UPLOAD_MAX_FILESIZE: '8M'
    volumes:
      - 'linkstack_data:/htdocs'
    ports:
      - '22223:443'
    restart: unless-stopped

volumes:
  linkstack_data:
